.\" -*- nroff -*-
.\" 
.\" This file was written by Eric Delaunay <delaunay@debian.org>.
.\" It is just a transcript of the README file from tilo-0.2.
.\" 
.TH TILO 1 "2001" "tilo"
.SH NAME
tilo \- Trivial Image LOader
.SH SYNOPSIS
.B tilo
.I [-o output]
.I <elf kernel images>
.I <root image>
.SH DESCRIPTION
.BI tilo
is a tool for building a simple TFTP boot loader
which embodies several kernel images for different Sun
architectures and a ramdisk root image. To minimize
memory usage, the images are gzipped. After starting
the boot loader, the architecture is detected, 
the appropriate kernel is unpacked and then the
booting procedure is launched.
.PP
.SH OPTIONS
.TP
.I <elf kernel images>
A list of either a single sun4cdm or sun4u image, or one of each.
.TP
.I <root image>
the initial ramdisk image to append to the kernel image.  It could be
compressed as well
.TP
.I <-o output>
The name of the output file to write the TILO image to. If not specified,
it will be \fBtftpboot.img\fR.
.PP
A boot image will be created which contains everything
necessary to boot on each architecture.
.SH NOTE
.B maketilo
is an internal command used by the
.B tilo
script.  There is no need to use it directly.
.SH AUTHOR
.B tilo
has been written by Jan Vondrak <jvon4518@barbora.mff.cuni.cz> and is now
maintained by Ben Collins <bcollins@debian.org>.
.SH AVAILABILITY
.B tilo
is available with the SILO package from
http://www.sparc-boot.org/.
